server:
  port: 8000

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #company sql
    #    url: jdbc:mysql://192.168.40.40:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    # url: jdbc:mysql://192.168.40.40:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #    username: pgsensing
    #    password: pg123456
    #home sql
    url: jdbc:mysql://localhost:3306/mybase?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml



